import Head from 'next/head'
import Navbar from './components/Navbar'
import { useState,useEffect } from 'react';
import setAuthToken from '../utils/jwttok';
import jwtDecode from 'jwt-decode';
import { useRouter } from 'next/router';
import axios from 'axios';
import Footer from './components/Footer';
import NewsCard from './components/NewsCard';
import Link from 'next/link';

export default function Home() {
  const [mount, setmount] = useState(false);
  const [news,setNews]=useState('')
const router=useRouter()
useEffect(() => {
  setmount(true);

  const getData = async () => {
          
   

    try {
   

  
      
      const res = await axios.get(`http://localhost:8800/news`);
 
      setNews(res.data);
     


    
     

       console.log("Data",res.data)
    } catch (err) {
      console.log(err);
    }
  };
  getData();


  
}, []);
let tokUser;
  if (mount){
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setAuthToken(jwt);
      tokUser = jwtDecode(jwt);
  }
    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet"/>
<link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' rel="stylesheet"/>
    <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js' rel="stylesheet"/>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js' rel="stylesheet"/>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css ' rel="stylesheet"/>

 
      </Head>
      <main>
        <Navbar/>
        <div className='hero' style={{display:'flex',justifyContent:'space-around', alignItems:'center'}}>
          <div className='text-section'>
          <span className='font big' style={{paddingTop:10}}>Изучай английский без границ 
с <span className='blue-font'> Englib!</span></span>
          <div className='start-buttons'>
          <button onClick={()=>router.push("/login")} className='start-button'><span>Приступить к обучению</span></button>

            <button  onClick={()=>router.push("#questions")} className='start-button q'><span>Вопросы и ответы</span></button>
          </div>
          <div className='info'>
            <div className='list-1'>
            <div className='list-p'><img src='./list.png'/><span>Удобство</span></div>
            <div className='list-p'><img src='./list.png'/><span>Круглосуточная работа</span></div>

            </div>
          <div className='list-1'>
          <div className='list-p'><img src='./list.png'/><span>Постоянные обновления</span></div>
            <div className='list-p'><img src='./list.png'/><span>Ориентированнность на студентов</span></div>

          </div>
           
          </div>

          </div>
            <img className='surfer' src="main.png"/>
        </div>
        <div style={{display:'flex', justifyContent:'center', gap:40}}>
          <div className='info-box'><span style={{fontSize:36}}>100+</span><span>студентов</span></div>
          <div  className='info-box y'><span style={{fontSize:36,color:'#4B52FB'}}>20+</span><span>преподавателей</span></div>

          <div  className='info-box'><span style={{fontSize:36}}>200+</span><span> материалов</span></div>

          <div  className='info-box y'><span style={{fontSize:36,color:'#4B52FB'}}>1000+</span><span> возможностей</span></div>


          
        </div>
        <div  id="newsline" className='main-section'>
        <h2>Новости и мероприятия</h2>
        <br/>
       {tokUser&& tokUser.job==1 &&< Link  style={{color:'black', display:'flex',  alignItems:'center',gap:3}} href='/addnews'>
          <img style={{height:30}} src="./add.png"/>
        <span>Опубликовать новость</span>
        </Link> }
        <hr/>
        
        {news? news.map((newsitem)=>{
          return(
            <NewsCard
            key={newsitem.nid}
            newsitem={newsitem}
            
            />
          )
        }):<div style={{alignSelf:'center',display:'flex',flexDirection:'column', alignItems:'center',gap:8}}><span>Пока новостей нет</span><img style={{height:300}} src='./nothing.jpg'/></div>}
     
       <div id="questions" style={{width:600,paddingBottom:40,paddingTop:60}}>
        <h3>Вопросы и ответы</h3>
        <hr/>
        <h4>В чем суть сервиса?</h4>
        <span>Englib - интернет-платформа БрГТУ кафедры иностранных языков, предоставляющая материалы учебно-методического комплекса  онлайн-словарь для помощи студентам</span>
        <hr/>
        <h4>Насколько актуальна информация на платформе?
</h4>
        <span>Материалы обновляются преподавателями по мере необходимости</span>
       <hr/>
        <h4>Кто является авторами материалов?</h4>
        <span>Преподаватели кафедры иностранных языков БрГТУ</span>
        
       </div>

        </div>
    
       
 
       
        <Footer/>
        
      </main>
      
    </>
  )}
  else {
    return null
  }
}
